# Generated by Django 4.0.5 on 2022-06-22 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='detal',
            new_name='detail',
        ),
    ]
