# Generated by Django 4.0.5 on 2022-06-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='payment_type',
            field=models.CharField(choices=[('card', '카드'), ('cash', '무통장 입금')], max_length=50, verbose_name='결제 방식'),
        ),
    ]
