# Generated by Django 4.0.5 on 2022-06-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_purchasehistory_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=30, verbose_name='이름'),
        ),
    ]
